@startuml
'https://plantuml.com/sequence-diagram

actor Manager
boundary ResetPasswordController
control UserService
boundary UserRepository

Manager -> ResetPasswordController: doGet(request, response)
ResetPasswordController -> UserService: findAll()
UserService -> UserRepository: findAll()
UserService <-- UserRepository
ResetPasswordController <-- UserService
ResetPasswordController -> ResetPasswordController: fillForm(form, users)
Manager <-- ResetPasswordController

Manager -> ResetPasswordController: doPost(request, response)
ResetPasswordController -> UserService: findById(id)
UserService -> UserRepository: findById(id)
UserService <-- UserRepository
ResetPasswordController <-- UserService
ResetPasswordController --> UserService: resetPassword(user)
UserService --> UserService: sendEmail(user)
ResetPasswordController <-- UserService
Manager <-- ResetPasswordController

@enduml