@startuml
'https://plantuml.com/class-diagram

class RegisterEmployeeForm {
    - username: String
    - password: String
    - name: String
    - jobTitle: String
    - managerId: Integer
    - managers: List<Manager>
}

class RegisterEmployeeController {
    + doGet(request: HttpServletRequest, response: HttpServletResponse): void
    + doPost(request: HttpServletRequest, response: HttpServletResponse): void
    - fillForm(form, employee): void
    - fillEmployee(form, employee): void
}

class UserService {
    + save(user: User): void
    + sendEmail(user: User): void
}

class UserRepository {
    + save(user: User): void
}

class EmployeeService {
    + save(employee: Employee): void
}

class EmployeeRepository {
    + save(employee: Employee): void
}

class ManagerService {
    + findAll(): List<Manager>
}

class ManagerRepository {
    + findAll(): List<Manager>
}

RegisterEmployeeController ..> RegisterEmployeeForm
RegisterEmployeeController *--> EmployeeService
EmployeeService *--> EmployeeRepository
RegisterEmployeeController *--> ManagerService
ManagerService *--> ManagerRepository
RegisterEmployeeController *--> UserService
UserService *--> UserRepository

@enduml